# Generated by Django 6.0.6 on 2026-06-17 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('license_renewal', 'License Renewal'), ('contract_expiry', 'Contract Expiry'), ('tax_deadline', 'Tax Deadline'), ('hr_obligation', 'HR Obligation')], max_length=30)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('overdue', 'Overdue'), ('resolved', 'Resolved')], default='upcoming', max_length=20)),
                ('notify_emails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='organizations.organization')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
    ]
