# Generated by Django 6.0.6 on 2026-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceevent',
            name='category',
            field=models.CharField(blank=True, help_text="Free-text obligation category for deadlines that don't fit the fixed type choices, e.g. 'CMA Disclosure', 'ESG Reporting', 'Internal Audit'.", max_length=100),
        ),
    ]
