# Generated by Django 6.0.6 on 2026-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comped',
            field=models.BooleanField(default=False),
        ),
    ]
