# Generated by Django 6.0.6 on 2026-06-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orguser',
            name='clerk_user_id',
        ),
        migrations.AddField(
            model_name='orguser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
