# Generated by Django 6.0.6 on 2026-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_internal_notes_and_more'),
        ('organizations', '0002_remove_orguser_clerk_user_id_orguser_password_and_more'),
    ]

    operations = [
    ]
