# Generated by Django 6.0.6 on 2026-06-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
        ('organizations', '0002_remove_orguser_clerk_user_id_orguser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformadmin',
            name='clerk_user_id',
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='org_user',
            field=models.OneToOneField(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='platform_admin', to='organizations.orguser'),
            preserve_default=False,
        ),
    ]
