# Generated by Django 6.0.6 on 2026-06-17 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jurisdiction', models.CharField(default='SA', max_length=10)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('law', 'Law'), ('regulation', 'Regulation'), ('guide', 'Guide')], max_length=20)),
                ('section_ref', models.CharField(blank=True, max_length=255)),
                ('content_excerpt', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10)),
                ('s3_key', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='organizations.orguser')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_summary', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('nda', 'NDA'), ('employment', 'Employment Contract'), ('freelance', 'Freelance Agreement'), ('vendor', 'Vendor Contract'), ('service', 'Service Agreement'), ('non_compete', 'Non-Compete Agreement'), ('warning_letter', 'Warning Letter'), ('termination_letter', 'Termination Letter')], max_length=30)),
                ('questionnaire_answers', models.JSONField(default=dict)),
                ('draft_content', models.TextField(blank=True)),
                ('exported_pdf_s3_key', models.CharField(blank=True, max_length=1024)),
                ('exported_docx_s3_key', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.orguser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('category', models.CharField(choices=[('liability', 'Liability'), ('termination', 'Termination'), ('confidentiality', 'Confidentiality'), ('ip', 'IP Ownership'), ('dispute_resolution', 'Dispute Resolution'), ('other', 'Other')], default='other', max_length=30)),
                ('recommendation', models.TextField(blank=True)),
                ('document_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='documents.documentanalysis')),
                ('citation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.knowledgesource')),
            ],
        ),
    ]
