# Generated by Django 6.0.6 on 2026-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
