# Generated by Django 6.0.6 on 2026-06-26 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_title', models.CharField(max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('embedder', models.CharField(default='placeholder', max_length=64)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
