from django.urls import path

from .views import (
    CancelSubscriptionView,
    ChangePlanView,
    ClientAuditView,
    ClientDetailView,
    ClientExportView,
    ClientListView,
    ClientNotesView,
    ClientPaymentsView,
    CompPlanView,
    MemberDetailView,
    PlatformAdminDeleteView,
    PlatformAdminsView,
    PlatformAuditView,
    PlatformStatsView,
    ReactivateSubscriptionView,
    RefundView,
    SuspendClientView,
)

urlpatterns = [
    path("backoffice/stats/", PlatformStatsView.as_view(), name="backoffice-stats"),
    path("backoffice/clients/", ClientListView.as_view(), name="backoffice-clients"),
    path("backoffice/clients/export/", ClientExportView.as_view(), name="backoffice-clients-export"),
    path("backoffice/clients/<uuid:org_id>/", ClientDetailView.as_view(), name="backoffice-client-detail"),
    path("backoffice/clients/<uuid:org_id>/payments/", ClientPaymentsView.as_view(), name="backoffice-client-payments"),
    path("backoffice/clients/<uuid:org_id>/audit/", ClientAuditView.as_view(), name="backoffice-client-audit"),
    path("backoffice/clients/<uuid:org_id>/change-plan/", ChangePlanView.as_view(), name="backoffice-change-plan"),
    path("backoffice/clients/<uuid:org_id>/comp-plan/", CompPlanView.as_view(), name="backoffice-comp-plan"),
    path("backoffice/clients/<uuid:org_id>/cancel/", CancelSubscriptionView.as_view(), name="backoffice-cancel"),
    path("backoffice/clients/<uuid:org_id>/reactivate/", ReactivateSubscriptionView.as_view(), name="backoffice-reactivate"),
    path("backoffice/clients/<uuid:org_id>/refund/", RefundView.as_view(), name="backoffice-refund"),
    path("backoffice/clients/<uuid:org_id>/suspend/", SuspendClientView.as_view(), name="backoffice-suspend"),
    path("backoffice/clients/<uuid:org_id>/notes/", ClientNotesView.as_view(), name="backoffice-notes"),
    path("backoffice/clients/<uuid:org_id>/members/<uuid:member_id>/", MemberDetailView.as_view(), name="backoffice-member"),
    path("backoffice/audit/", PlatformAuditView.as_view(), name="backoffice-audit"),
    path("backoffice/admins/", PlatformAdminsView.as_view(), name="backoffice-admins"),
    path("backoffice/admins/<uuid:admin_id>/", PlatformAdminDeleteView.as_view(), name="backoffice-admin-delete"),
]
